#System Configuration
server.port: 18777
spring:
  datasource:
    mysql:
      url: jdbc:mysql://192.168.4.223:3306/adserver?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
#Custom Configuration
app:


